version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: .docker/base.Dockerfile
    ports:
      - 5000:3000
    volumes:
      - .:/opt/mediabyte/app
    command: shell
    environment:
      DEBUG: "True"
    links:
      - postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6.0.10-alpine
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mediabyte
      - POSTGRES_PASSWORD=mediabyte
      - POSTGRES_DB=app

volumes:
  redis_data:
  postgres_data:
